### ISSUE TITLE
(March 30th) provide TLS certificates for the Traefik proxy

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/cau-client#2]
share these certificates via a Docker volume.

At the moment, Traefik is using self-signed certificates, generated via:
`openssl req  -nodes -new -x509  -keyout server.pem -out server.crt`

**Comment by syc17** [comment]
Just to provide more description of this task.  Sarang and I agreed that it may be simplest to let the Reverse Proxy use the Agent's certificate as each agent only runs 1 reverse proxy and the reverse proxy only uses the certificate for TLS communication (point-2-point encryption) but not server/client authorisation.  Cris confirms that there is no specific constraint on the CN.  This task involves updating the CAU client's docker file to declare a shared volume with the host and update the CAU client's code to store the signed certificate and the associated private key to this shared volume.

**Comment by syc17** [comment]
Updated code and cau-client docker file.  The credentials (private key and x509 cert) are written to a shared data volume (pkidata).  I need to test the container next.

**Comment by syc17** [comment]
I have checked that the volumes are set up OK to share files.  The image tag is mf2c/cau-client:v1.02.  I have updated the it2 dockercompose.yml (https://github.com/mF2C/mF2C/blob/master/docker-compose/docker-compose.yml) wrt the cau-client and volumes sections.  Cris will need to add the RO volume mapping to the traefik section.  Note that the files are server.key (RSA private key) and server.crt (X.509 cert)

**Comment by cjdcordeiro** [comment]
cool.

but you've modified the wrong file in mf2c/mf2c

The up to date compose file is docker-compose-it2.

Pushes to master have now been disabled so you'll need to make a PR

**Comment by syc17** [comment]
I did look at docker-compose-it2, but all the discovery bits (including cau-client) are commented out.  Do you want me to update that one regardless?  Also, not sure what you mean by 'make a PR'.  Could you please explain? Ta

**Comment by cjdcordeiro** [comment]
yes that's the one to be updated. if the cau-client is not fully integrated with eveyrthing else, then keep it commented by add the volume anyway

PR = pull request. This is to avoid pushing changes directly to master without testing the full compose file
