### ISSUE TITLE
(May 1st) provide ARM compliant registration components for the microagent

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/cau-client#3]
need:
 - discovery, identification and cau-client

depends on https://github.com/mF2C/ResourceManagement/issues/21

**Comment by syc17** [comment]
My understanding from the meeting is that micro-agent needs to use the CAU-client to get a certificate from the cloud CA for identification.  To implement the process, the CAU client would require:

1) upstream to provide a CN for generating the CSR.  (In a full agent, the Policy block provides a truncated device-id)
2) a CAU ip address (we could use a fixed port on 127.0.0.1 or the cloud CAU if none is provided)

The process assumes that validation is performed somewhere else.  In a full agent, this is done by the Policy block (?).  Cris said at the meeting that he will discuss this with UPC and there is no need for the CAU Client to care about validating the certificate request is from a genuine mF2C 'device'

**Comment by cjdcordeiro** [comment]
@ALEJANDROJ19 who validates that an agent is legitimate?

**Comment by ALEJANDROJ19** [comment]
@cjdcordeiro that would be the CAU and the CAU client receives this validation when receiving the certificates. Am I wrong @mrsarang ?

**Comment by mrsarang** [comment]
Yes that's right , when cau recieve from ca the certificate it send device id to leader and signed certificate to microagent

**Comment by syc17** [comment]
Please refer to figure 6 in D5.1.  Leader.Discovery cache the 'new' agent's deviceID and authentication status which is updated later by the Leader.CAU.  The local CAU on receiving the signed certificate calls the Leader.CAU to update the authentication status flag.

**Comment by ALEJANDROJ19** [comment]
As I said i my last message, CAU validates the agent (meaning that it sends to the leader a message to update this status in the database (CIMI - DC)) and the agent itself knows if its validated by receiving the certificate (this step is obvious).

**Comment by syc17** [comment]
No, I don't think it is obvious FROM the sequence diagram.  The Leader.CAU does not return anything to the local CAU.  So the local CAU does not know if the update is successful or failed.  Obviously, I don't know what you have actually implemented.  The sequence diagram shows that the local CAU just carries on to return the signed certificate to the CAU client w/o knowing what the update status is.

**Comment by ALEJANDROJ19** [comment]
If the leader fails to add the update to the CIMI - DB, means that the Leader is not behaving correctly (e.g. the leader is down), and the area needs some reorganisation (aka. new leader elected). The agent will be able to detect this by trying to connect to the leader and failing.  However, this diagram is only showing a normal behaviour, not extreme/failure cases.

**Comment by syc17** [comment]
OK.   Should the CAU not fail the process at that point rather than carrying on and let the new Agent trying to connect to the leader (CAU)?  There could be other reasons for failing to connect to the leader (CAU).  Seems better for debugging runtime errors.

**Comment by syc17** [comment]
Cris,  before I change the CAU-client code to support the micro-agent in getting a X.509 certificate, I just want to remind you on the info required by the CAU-client:
1) on starting up:
1a) ip:port of detected leader CAU
1b) ip:port of local CAU (could be fixed as discussed above)

2) at runtime, the Policy block provides these arguments:
2a) detected leader MACaddress
2b) detected leader ID
2c) (this) agent's device ID
2b) (this) agent's ID key (up to 64 char) - this is used as the commonname in the certificate.

If all data items can be provided, then there is no need to change the code.  Is the micro-agent going to adopt the same registration and authentication process flow as the full agent?

**Comment by cjdcordeiro** [comment]
So, 

1. 
   1a) this is only needed if the VPN server exists. Otherwise you cannot reach out to the leader CAU
   1b) sure. It will always be the cloud CAU and can be passed via env variable

2. only 2b) seems tricky, for the same reasons as 1a) above.

I'm not sure about the flow, but the what I can say is that the purpose of the registration is different than for regular agents. For now, we only care about validating the microagent...and not securing it.

**Comment by syc17** [comment]
I feel it is not appropriate just to issue a certificate to a device w/o really understanding what the registration workflow (and thus the security risks) is.  It is better if we could step through the process first.   The full agent registration/authentication flow is defined in D3.2 figure 4.  Is the micro-agent bootstrapped in a different way to a full agent?  How does a micro-agent 'discovers' a leader?

**Comment by cjdcordeiro** [comment]
at this stage, we don't care about certificates for the microagent. 

Step 1 - I want to make my RPi part of mF2C. So you need to provide a way for **validating** that my RPi is entitled to join mF2C and execute workflows. 

Step 2 - my RPi is a leader...the only thing above him is the mF2C Cloud Agent

so your key takeaway is: the microagent will not use any certificates, so it doesn't care if you issue them or not. It just wants to become a legit mF2C device

**Comment by syc17** [comment]
Sorry, I am getting rather confused over this business.  If your RPi always functions/joins as a leader, then I presume (UPC comment please) that the device owner has registered the RPi has a valid device with the cloud registration service, then mF2C has the deviceID etc. in its registration database.  This is similar to the Full Agent registration flow.  To be honest, I don't think there is a clear sequence diagram on the registration process for a leader agent.

**Comment by syc17** [comment]
Update: 
1.  Jens is providing me with a Rpi (Cherry) which is an "ARMv7" processor for testing the crypto functions used by cau-client and security lib.  
2.  Not planning to change CAU client code as Cris seems to be more interested in getting the agent on the RPi validated than getting a certificate.  This seems to me more about registration than certification, so in UPC area.  Could Alejandro comment, please.

**Comment by ALEJANDROJ19** [comment]
As I understood, we need a customised flow for the microagents that provide discovery, identification and validation (or authentication (?)) on startup. From the meeting in Barcelona i understood that Discovery is a different mechanism than in the normal agent due the hardware limitations, but Identification remains exactly the same.

Here we have the issue (#21)[https://github.com/mF2C/ResourceManagement/issues/21] to make an ARM compatible image of the Identification module. With that, the micro-agent will get a valid deviceID and @alxjand is in charge.

For the other comments, I'm a quite lost in the discussion.

**Comment by cjdcordeiro** [comment]
thanks @ALEJANDROJ19 that's a good start. as for #21, we'll need the same for every module involved in the agent registration

**Comment by syc17** [comment]
Got my Rpi set up, awaiting network connection from our PCSupport people

**Comment by syc17** [comment]
I have compiled a version of cau-client against the ARMv7 Processor rev4.  The code is running, but slower than on other machines.   It can create a CSR using the bouncycastle libs, but it took 3 mins to do so. 
But before I make any changes, I need to know what exactly is required of the CAU-Client for the micro-agent discovery process: e.g. Cris mentioned that it is not necessary to get a certificate for a micro-agent

**Comment by syc17** [comment]
pushed mf2c/cau-client-arm:v1.00-SNAPSHOT image and tagged it as the latest version to docker hub.   The code is the same for the full agent and as I mentioned above, I need to understand what is required of cau-client in the micro-agent discovery and authentication etc process before I can make any changes to optimise it.

**Comment by syc17** [comment]
Here is a straw man of an ident & authen flow for the microagent.  It just represents my understanding of what Cris want, it is by no means complete or even accurate.  I would like others to have a go at improving/rewriting this:
![image](https://user-images.githubusercontent.com/10448958/57092256-e58b8900-6d02-11e9-9b95-9cc57ea6208c.png)
Some issues to consider:
1) is the Slipstream Nano a micro-agent and can it support the process as it is (e.g. handle cert)
2) I haven't put in much about the leader discovery as I don't know how this works for micro-agent
3) I haven't covered traefik's operation here.  The cert is written to the 'pkidata' share file volume for it to pick up
4) I assume that the user got the idKey through registering for mF2C in the cloud
5) I don't know what happen AFTER the micro-agent established VPN connection to a leader.  What info does the leader needs to authenticate the micro-agent etc.

**Comment by cjdcordeiro** [comment]
Thanks . Please share the raw diagram so I can edit it

**Comment by syc17** [comment]
New version with both Cris and my changes, still need more work:
![image](https://user-images.githubusercontent.com/10448958/57141402-06f77e00-6db2-11e9-80e4-9cc6261cb564.png)
And the issues (see previous diagram) still need to be taken into consideration.

**Comment by cjdcordeiro** [comment]
1st blue box: discovery is needed for cases where an external NIC exists. 
2nd blue box: what's the question? the involved components are already in the picture.  (9May19 SYC: this is obsolete.  The VPN client is running a set up script to generate the .opvn config file)

Issues: 
 1. is the NuvlaBox Nano a micro-agent and can it support the process as it is (e.g. handle cert) => yes
 2. haven't put in much about the leader discovery as I don't know how this works for micro-agent => covered by discovery
 3. haven't covered traefik's operation here. The cert is written to the 'pkidata' share file volume for it to pick up => nothing to cover
 4. assume that the user got the idKey through registering for mF2C in the cloud => yes
 5. don't know what happen AFTER the micro-agent established VPN connection to a leader. What info does the leader needs to authenticate the micro-agent etc. => no need to worry about that, cause the leader is also connected to the VPN, so they can see each other

**Comment by syc17** [comment]
No comments from UPC?

**Comment by ALEJANDROJ19** [comment]
Some comments regarding the flow:

- Identification doesn't directly triggers CAU-client, but it's not something to worry about because the one that sending messages will follow the CAU-client API specifications.
-  Identification needs two messages to provide the deviceID. First the trigger that starts the registration of the device (and generates the deviceID) and then the second message to get the deviceID each time that is needed.

> [GET] Start Trigger: `http://identification:46060/api/v1/resource-management/identification/registerDevice/`
> [GET] get deviceID message: `http://identification:46060/api/v1/resource-management/identification/requestID/`
>To any issues or concerns about Identification module, please contact to @alxjand

**Comment by syc17** [comment]
@alxjand It would help to complete the picture if you could update the sequence diagram (see below) with who is triggering the CAU-client or who orchestrate the flow, and incorporate @ALEJANDROJ19 comments above.  It helps to clarify the dependency between modules and also make sure that we have a common understanding of the modules' roles and responsibilities.  Please ping me privately if you want me to send you a copy of the original powerpoint picture.  Thanks.

![image](https://user-images.githubusercontent.com/10448958/57522812-0c594900-731b-11e9-9371-cded543965cb.png)

**Comment by ALEJANDROJ19** [comment]
From the workflow above @syc17 , neither the discovery or the identification are orchestrating anything. The microagent [script](https://github.com/mF2C/mF2C/blob/master/docker-compose-microagent/mf2c-entrypoint.sh) takes care about all the different messages and triggers.

**Comment by ALEJANDROJ19** [comment]
Code from Policies AgentStart.py regarding the trigger to CAU client:

```python3
s_caucl = socket.socket(socket.AF_INET, socket.SOCK_STREAM)     # Define socket timeout!
s_caucl.connect(CPARAMS.CAU_CLIENT_ADDR)
s_caucl.send('detectedLeaderID={},MACaddr={},IDkey={},deviceID={}\n'.format(self.detectedLeaderID,self.MACaddr,str(self.IDkey)[:64],self.deviceID).encode())
reply = s_caucl.recv(4092).decode()
s_caucl.close()
```

**Comment by syc17** [comment]
Thank you, this is helpful.   But

1.  can I clarify the meaning of the arguments that UPC are providing?
DetectedLeaderID = deviceID of the leader (generated by Identity)
IDKey = 128 bit IDKey provided as an environmental argument to the Docker-compose.yml script
deviceID = the new Agent's deviceID (generated by Identity)
MACaddr = MACaddr of the new Agent

2.  If it is possible, could CAU client has the full size IDs?  i.e. please do not truncated them to 64 chars, CAU-client will do the truncation.  It will store the full IDs to help with looking up public keys.   Also, we need the full idKey because it needs to be validated against the cloud CIMI/Dataclay.  Could you please let me know if Policy can send CAU-Client the full size IDs?

3.  Cris, FYI, the docker compose script contains the IPs that need to be provided to launch the CAU-client

Thanks

**Comment by syc17** [comment]
> From the workflow above @syc17 , neither the discovery or the identification are orchestrating anything. The microagent [script](https://github.com/mF2C/mF2C/blob/master/docker-compose-microagent/mf2c-entrypoint.sh) takes care about all the different messages and triggers.

@ALEJANDROJ19 @cjdcordeiro  I checked the script Alejandro referenced, it looks like it is Cris' script to start a RPi agent for the summer school demo as it contains hardcode.  Not sure that it can be used for 'real'.  But I presume there will be a docker-compose script for installing a micro-agent and this can be the trigger in the last diagram.

Feel free to comment

**Comment by cjdcordeiro** [comment]
where is the hardcode?

**Comment by syc17** [comment]
Sorry, may be I am using the term too imprecisely from your POV, apology.  The hardcode refers to the assumption that the RPI agent is always a leader.  Also, if the no usename/pswd is available, you are using the Slipstream admin privilege (listed in the clear) to login to the cloud dashboard.
I can see your script launches a life-cycle manager container.  Does this mean the life-cycle manager will trigger all the rest of the process (e.g. get an Agent Certificate ..)?   In that case, we should change the diagram above to make sure we have the same understanding.

**Comment by syc17** [comment]
Regarding the trigger, see Alejandro's comment [https://github.com/mF2C/cau-client/issues/3#issuecomment-491274825](url)  FYI, D4.4 Section 9.2.2 mentioned that Identification triggers the CAU-based registration.

**Comment by cjdcordeiro** [comment]
@syc17 @ALEJANDROJ19 can you please provide the compose file with the arm tags for this? (containing all the components in the pipeline for the registration)

**Comment by ALEJANDROJ19** [comment]
Hi @cjdcordeiro , here you have the endpoints for the Identification module. Please @alxjand verify that everything is correct.

Register Agent
`GET /api/v1/resource-management/identification/registerDevice/` 
Expected result: Reply can be that Agent is registered or that the registration is already done.

Get deviceID and idKey:
`GET /api/v1/resource-management/identification/requestID/`
Expected Result: JSON with `deviceID` and `IDKey`

Register must be executed once at the beginning.

**Comment by cjdcordeiro** [comment]
what's the service handling this? what's the base url?

**Comment by ALEJANDROJ19** [comment]
base url should be the identification container, and the port is 46060.

**Comment by cjdcordeiro** [comment]
so I need that container built for ARM

**Comment by ALEJANDROJ19** [comment]
`identification:ARM` https://cloud.docker.com/u/mf2c/repository/docker/mf2c/identification/tags

**Comment by syc17** [comment]
cau-client it2 version : mf2c/cau-client-it2-arm:v1.1

**Comment by syc17** [comment]
cau-client and openVPN  have been tested by Zeineb see https://github.com/mF2C/mF2C/issues/135

**Comment by cjdcordeiro** [comment]
just missing resource-categorization @ssgUPC , then this can be closed

**Comment by ssgUPC** [comment]
The `ARM` version docker-image for resource-categorization module is `latest-V2.0.18-arm`. 

N.B.- For this image, to get the device IP still, we are using a separate container (Alpine).
